SET DATABASE SQL SYNTAX ORA TRUE;
DROP SCHEMA IF EXISTS TEST CASCADE;

CREATE SCHEMA TEST;

DROP SEQUENCE IF EXISTS SEQ_T_PIGGYURL;

DROP TABLE IF EXISTS T_PIGGYURL;

CREATE SEQUENCE SEQ_T_PIGGYURL START WITH 3 INCREMENT BY 1;

CREATE TABLE T_PIGGYURL
(
"ID" NUMBER(5, 0) NOT NULL,
"CODE" VARCHAR2(200),
"DESCRIPTION" VARCHAR2(200),
PRIMARY KEY("ID")
);

DROP SEQUENCE IF EXISTS SEQ_T_USER;

DROP TABLE IF EXISTS T_USER;

CREATE SEQUENCE SEQ_T_USER START WITH 2 INCREMENT BY 1;

CREATE TABLE T_USER
(
"USER_ID" NUMBER(5, 0) NOT NULL,
"USER_NAME" VARCHAR2(200) NOT NULL,
"USER_PASSWORD" VARCHAR2(200) NOT NULL,
"USER_FIRSTNAME" VARCHAR2(200) NOT NULL,
"USER_LASTNAME" VARCHAR2(200),
"USER_MAIL" VARCHAR2(200) NOT NULL,
"USER_RIGHT_LEVEL" VARCHAR2(200) NOT NULL,
"GROUP_FT_ID" NUMBER(5, 0),
"GROUP_TB_ID" NUMBER(5, 0),
"USER_CREATION_DATE" date NOT NULL,
"CREATED_BY_USER_ID" NUMBER(5, 0) NOT NULL,
PRIMARY KEY("USER_ID")
);

DROP SEQUENCE IF EXISTS SEQ_T_GROUP;

DROP TABLE IF EXISTS T_GROUP;

CREATE SEQUENCE SEQ_T_GROUP START WITH 3 INCREMENT BY 1;

CREATE TABLE T_GROUP
(
"GROUP_ID" NUMBER(5, 0) NOT NULL,
"GROUP_NAME" VARCHAR2(200) NOT NULL,
"GROUP_TYPE" VARCHAR2(200) NOT NULL,
PRIMARY KEY("GROUP_ID")
);

DROP SEQUENCE IF EXISTS SEQ_T_CARD;

DROP TABLE IF EXISTS T_CARD;

CREATE SEQUENCE SEQ_T_CARD START WITH 1 INCREMENT BY 1;

CREATE TABLE T_CARD
(
"CARD_ID" NUMBER(5, 0) NOT NULL,
"ORIGINAL_URL" VARCHAR2(2000) NOT NULL,
"SHORT_URL" VARCHAR2(2000) NOT NULL,
"DESCRIPTION" VARCHAR2(2000),
"GROUP_ID" NUMBER(5, 0),
"CREATE_USER_NAME" VARCHAR2(200) NOT NULL,
"APPROVE_USER_NAME" VARCHAR2(200),
"APPROVED" VARCHAR2(1) NOT NULL,
"URL_CREATION_DATE" date NOT NULL,
"URL_EXPIRATION_DATE" date,
PRIMARY KEY("CARD_ID")
);

DROP SEQUENCE IF EXISTS SEQ_T_CARD_UPDATE;

DROP TABLE IF EXISTS T_CARD_UPDATE;

CREATE SEQUENCE SEQ_T_CARD_UPDATE START WITH 1 INCREMENT BY 1;

CREATE TABLE T_CARD_UPDATE
(
"CARD_UPDATE_ID" NUMBER(5, 0) NOT NULL,
"CARD_ID" NUMBER(5, 0) NOT NULL,
"APPROVER_USER_NAME"  VARCHAR2(200) NOT NULL,
"BEFORE_UPDATE"  VARCHAR2(20000) NOT NULL,
"AFTER_UPDATE"  VARCHAR2(20000) NOT NULL,
PRIMARY KEY("CARD_UPDATE_ID")
);

INSERT INTO T_PIGGYURL(ID, CODE, DESCRIPTION) VALUES(1, 'A', 'Twinkle twinkle little star');
INSERT INTO T_PIGGYURL(ID, CODE, DESCRIPTION) VALUES(2, 'B', 'Johnny Johnny Yes Papa');

INSERT INTO T_GROUP(GROUP_ID,GROUP_NAME,GROUP_TYPE) VALUES(1, 'FeatureTeam1', 'FEATURE_TEAM');
INSERT INTO T_GROUP(GROUP_ID,GROUP_NAME,GROUP_TYPE) VALUES(2, 'Tribe1', 'TRIBE');

INSERT INTO T_USER(USER_ID, USER_NAME, USER_PASSWORD, USER_FIRSTNAME, USER_LASTNAME, USER_MAIL, USER_RIGHT_LEVEL, GROUP_FT_ID, GROUP_TB_ID, USER_CREATION_DATE, CREATED_BY_USER_ID)
VALUES(1, 'ashish.raj', 'ashish@123', 'Ashish', 'Raj', 'er.ashishraj2010@gmail.com', 'ADMIN', 1, 2, '2000-01-01', 1);
