language: java
install: true
jdk: openjdk11
dist: xenial
notifications:
  email: false
# only build for commits/pr targeted to master branch
# this avoid duplicate builds for push+PR
branches:
  only:
    - master
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.m2
deploy:
  provider: heroku
  api_key:
    secure: 03cae514-a76c-4e09-b1e8-ed458fddbd72
  app: piggyurl
  on:
    repo: er-ashishraj/piggyurl
